# Generated by Django 3.2.9 on 2021-12-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='value',
            field=models.CharField(max_length=128),
        ),
    ]
