# Generated by Django 3.2.9 on 2021-12-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('slug', models.SlugField()),
                ('category_image', models.ImageField(blank=True, upload_to='images/category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
